HANGMAN_WORDS = [
    "python", "developer", "programming", "algorithm", "function",
    "variable", "iteration", "condition", "loop", "syntax",
    "compile", "debug", "exception", "parameter", "recursion",
    "string", "integer", "boolean", "dictionary", "list",
    "tuple", "array", "object", "method", "inheritance",
    "polymorphism", "encapsulation", "abstraction", "module", "package",
    "framework", "database", "query", "index", "key",
    "value", "network", "protocol", "encryption", "security",
    "hardware", "software", "interface", "design", "architecture",
    "cloud", "virtualization", "container", "repository", "version",
    "control", "branch", "merge", "commit", "push",
    "pull", "fork", "clone", "execute", "compile",
    "lambda", "decorator", "generator", "comprehension", "multithreading",
    "asynchronous", "synchronous", "client", "server", "request",
    "response", "json", "xml", "api", "endpoint",
    "token", "authentication", "authorization", "session", "cookie",
    "frontend", "backend", "fullstack", "deployment", "hosting",
    "debugging", "testing", "unittest", "integration", "continuous",
    "delivery", "pipeline", "automation", "script", "console",
    "terminal", "command", "argument", "parameter", "environment"
]
